# -*- coding: utf-8 -*-
"""my code .1py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igI2386fnzEl2YS3205pJ4yIhoiLulDB
"""

#write a program to enter two number and add their sum
a=int(input("Enter the number"))
b=int(input("enter the number"))
sum=a+b
print("sum of numbers:",sum)

#write a program to input side of square and find its area
side=int(input("enter the  side of square"))
area=side*side
print("area of square:",area)

#write a program to input 2 floating number and find its average
a=float(input("enter the number"))
b=float(input("enter the number"))
avg=(a+b)/2
print("average is :",avg)

#write a program to input 2  integer number a & b printtrue if a is greater than or equal to b if not print false
a=int(input("enter  the number"))
b=int(input("enter the number"))
print(a>=b)

